### ISSUE TITLE
Вылет редактора

### ISSUE THREAD

**Issue by lnobad** [ufna/VaFogOfWar#105]
Владимир, Здравствуйте! Редактор вылетает при переходе в плеймод.

Настраивал по этой - [инструкции](https://www.notion.so/How-To-Setup-Your-Own-Fog-Of-War-507bdb7eb6ce4fa1a75e51b28ef99754)

Unhandled Exception: 0xe06d7363
msvcp140
UE4Editor_VaFogOfWar!AVaFogLayer::UpdateUpscaleBuffer() [d:\build\++portal+dev-marketplace+full\sync\localbuilds\plugintemp\hostproject\plugins\vafogofwar\source\vafogofwar\private\vafoglayer.cpp:545]
UE4Editor_VaFogOfWar!AVaFogLayer::UpdateBuffers() [d:\build\++portal+dev-marketplace+full\sync\localbuilds\plugintemp\hostproject\plugins\vafogofwar\source\vafogofwar\private\vafoglayer.cpp:365]
UE4Editor_Engine!AActor::TickActor() [d:\build\++ue4\sync\engine\source\runtime\engine\private\actor.cpp:996]
UE4Editor_Engine!FActorTickFunction::ExecuteTick() [d:\build\++ue4\sync\engine\source\runtime\engine\private\actor.cpp:168]
UE4Editor_Engine!FTickFunctionTask::DoTask() [d:\build\++ue4\sync\engine\source\runtime\engine\private\ticktaskmanager.cpp:285]
UE4Editor_Engine!TGraphTask<FTickFunctionTask>::ExecuteTask() [d:\build\++ue4\sync\engine\source\runtime\core\public\async\taskgraphinterfaces.h:847]
UE4Editor_Core!FNamedTaskThread::ProcessTasksNamedThread() [d:\build\++ue4\sync\engine\source\runtime\core\private\async\taskgraph.cpp:686]
UE4Editor_Core!FNamedTaskThread::ProcessTasksUntilIdle() [d:\build\++ue4\sync\engine\source\runtime\core\private\async\taskgraph.cpp:594]
UE4Editor_Engine!FTickTaskSequencer::ReleaseTickGroup() [d:\build\++ue4\sync\engine\source\runtime\engine\private\ticktaskmanager.cpp:577]
UE4Editor_Engine!FTickTaskManager::RunTickGroup() [d:\build\++ue4\sync\engine\source\runtime\engine\private\ticktaskmanager.cpp:1528]
UE4Editor_Engine!UWorld::RunTickGroup() [d:\build\++ue4\sync\engine\source\runtime\engine\private\leveltick.cpp:782]
UE4Editor_Engine!UWorld::Tick() [d:\build\++ue4\sync\engine\source\runtime\engine\private\leveltick.cpp:1567]
UE4Editor_UnrealEd!UEditorEngine::Tick() [d:\build\++ue4\sync\engine\source\editor\unrealed\private\editorengine.cpp:1683]
UE4Editor_UnrealEd!UUnrealEdEngine::Tick() [d:\build\++ue4\sync\engine\source\editor\unrealed\private\unrealedengine.cpp:410]
UE4Editor!FEngineLoop::Tick() [d:\build\++ue4\sync\engine\source\runtime\launch\private\launchengineloop.cpp:4485]
UE4Editor!GuardedMain() [d:\build\++ue4\sync\engine\source\runtime\launch\private\launch.cpp:173]
UE4Editor!GuardedMainWrapper() [d:\build\++ue4\sync\engine\source\runtime\launch\private\windows\launchwindows.cpp:134]
UE4Editor!WinMain() [d:\build\++ue4\sync\engine\source\runtime\launch\private\windows\launchwindows.cpp:263]
UE4Editor!__scrt_common_main_seh() [d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll

**Comment by ufna** [comment]
Привет!

Нужен проект с воспроизведением. По точке краша - совершенно хз что могло пойти не так, к сожалению. Выглядит так, что GC что-то успел подожрать, когда не должен был.

**Comment by lnobad** [comment]
А вот и проект -  https://github.com/lnobad/VaFogOfWarTest.git

**Comment by ufna** [comment]
![image](https://user-images.githubusercontent.com/271578/80719716-8c685800-8b04-11ea-8679-94f880a6d036.png)

Here is the reason. Blocking volume should be applied to Terrain level only (VaFogTerrainLevel class)

**Comment by ufna** [comment]
Все, заработался, на английском уже отвечаю на автомате.

Короче, блокинг вольюмы - они только для применения "на землю". Я класс переменной поправлю, чтобы нельзя было туда просто layer воткнуть.

**Comment by lnobad** [comment]
Спасибо!

**Comment by ufna** [comment]
Не за что, я чет упустил этот момент. Завел #107 , подумаю отдельно на праздниках. 

Спасибо за репорт и тестовый проект! Если нужна "полная" гусевая демка с настроенным туманом - пингани на почту, пришлю в качестве компенсации за рисеч :)
