### ISSUE TITLE
Вопрос по UE4 из ваших лекций

### ISSUE THREAD

**Issue by Valeryn4** [ufna/VaFogOfWar#113]
Добрый день!
Я видел ваши лекции от мейл ру: https://www.youtube.com/watch?v=kAdP9AdQ5jw
Вы говорили, пишите мол на гитхаб, задавайте вопросы. Куда задать именно не знаю, но есть вопрос.

Как вы используете и используете от UE4 абилити систем?
Каких паттернов вы придерживаетесь? Реализуете в лоб или придерживаетесь каких то паттернов?

Так же вопрос по логике. Вы логику реализуете прям в акторе, т.е. пишите функции в акторе и подключаете к ивентам эти функции в акторе или же вы реализуете логику непосредственно в компонентах? Я очень большой сторонник ECS и придерживаюсь стороны, мол актор - абстракция и абстракцией должна оставаться, а логика только и только должна быть в компонентах. Но почти во всех лекциях и гайдах народ в лоб штампует логику прям в актор, порождая год-обьекты.
Вот пример:
- Делаем мы оружие. Оружие - актор. Чаще всего, стрельба, перезарядка, генерация снарядов - строится в акторе.
Вы предпочитаете делать эту логику в компонентах, например компоненты "Ган-компонент", "Релоад-компонент" и допустим "Буллет параметр-компонент"? Так же наступает сложность, как компонентам правильно общаться друг с другом? Какой паттерн вы юзаете, для общения между компонентами, что бы ган компонент знал, что он не шлет ивент, пока релоад компонент отрабатывает логику перезарядки со своими таймингами?

**Comment by ufna** [comment]
@Valeryn4 , добрый день!

Писать лучше напрямую мне, контакты на https://ufna.dev/resume :) Здесь я топик закрою, все-таки это место для саппорта конкретного плагина.

> Как вы используете и используете от UE4 абилити систем?
> Каких паттернов вы придерживаетесь? Реализуете в лоб или придерживаетесь каких то паттернов?

Нет, не используем. GAS выглядит оверкиллом для большинства случаев - это не серебрянная пуля, это в целом фреймворк для абилок под системы аля РПГ. Для простых игр он слишком сложен, для сложных - часто требует либо модификации, либо обкладыванием костылями. Так что очень зависит от проекта, некоторым он просто ОЧЕНЬ подходит :) 

> Так же вопрос по логике. Вы логику реализуете прям в акторе, т.е. пишите функции в акторе и подключаете к ивентам эти функции в акторе или же вы реализуете логику непосредственно в компонентах? Я очень большой сторонник ECS и придерживаюсь стороны, мол актор - абстракция и абстракцией должна оставаться, а логика только и только должна быть в компонентах. Но почти во всех лекциях и гайдах народ в лоб штампует логику прям в актор, порождая год-обьекты.

GOD-объекты это плохо, мы разделяем их на компоненты по мере работы. Но в целом - логика пишется в самих экторах, нужды разбивать их на компоненты ради любви к искусству нет (если конечно это не реиспользуемый блок, который можно садить в кучу разных экторов). Достигли некоторого размера, который становится опасным - рефакторинг, выделение компонентов. 

Очень рекомендую статью https://caseymuratori.com/blog_0015 , мы используем близкий подход. Исключение - это performance-critical системы, которые мы заранее знаем что будут боттлнеком - они проектируются в деталях заранее.
