### ISSUE TITLE
Erase fog 

### ISSUE THREAD

**Issue by blakewj** [ufna/VaFogOfWar#114]
any word on this feature? I've tried clearing the rt's but that dosnt solve the issue. If you can at the least tell me where to look ill patch if myself. We are close to release and I really don't want to have to remove this plugin before shipping

**Comment by ufna** [comment]
Hi @blakewj ,

Are you speaking of erasing all uncovered areas, or "reveal all"?

**Comment by blakewj** [comment]
Yes, both.
erase all uncovered areas and the opposite to fill all areas.
Essetially a way to clear all the render targets during runtime, and a way to fill all the render targets.

I would also  like a way to have an actor draw the fog in example: I have an actor that spawns fog instead or erasing when moving around the scene.
Would that be possible?

**Comment by ufna** [comment]
I've added two function to cover/reveal layer at once, please check it.

Regarding "fog actor" it's not supported for now, please open another issue with feature description, I'll take a look a bit later.

**Comment by blakewj** [comment]
Thanks for that.

I check it put shotly.
